### ISSUE TITLE
Compile error: ‘AVCODEC_MAX_AUDIO_FRAME_SIZE’ undeclared here (not in a function)

### ISSUE THREAD

**Issue by ViktorNova** [ayyi/samplecat#10]
After it compiles for awhile, I'm getting this error Arch Linux from samplecat in the AUR:
````
audio_decoder/ad_ffmpeg.c:27:32: error: ‘AVCODEC_MAX_AUDIO_FRAME_SIZE’ undeclared here (not in a function)
````
I can provide more info if needed

**Comment by ayyi** [comment]
Hi, commit de9b4a68908ea85c0e98682c3388d9c32858e43f defines AVCODEC_MAX_AUDIO_FRAME_SIZE if missing. This _may_ hopefully fix things for users of newer versions of ffmpeg. I will create a new release in the next few days so that Arch users may benefit from this fix.
Many thanks for reporting the issue.
