### ISSUE TITLE
segfault on start

### ISSUE THREAD

**Issue by mxmilkiib** [ayyi/samplecat#55]
https://gist.github.com/mxmilkiib/1dde8375b310ab9ab91de7b921597b5b

**Comment by ayyi** [comment]
Hi

Thanks for the coredump.

I can't tell much because samplecat was apparently built without debugging symbols, but it is during loading of the config files. The config files recently changed from XML to YAML.

Did you get the segfault immediately after updating?

Could you post the contents of the file `~/.config/samplecat/layouts/__default__.yaml` ?

You could also try copying the file at `https://github.com/ayyi/samplecat/blob/master/layouts/__default__.yaml` to the directory `~/.config/samplecat/layouts/` to see if that helps.

**Comment by mxmilkiib** [comment]
I deleted the config and the app starts.

**Comment by ayyi** [comment]
Glad you have it working now.

If it happens again, please post the offending config as there is clearly an issue that needs to be addressed as the application should not segfault on bad config.

Cheers
