### ISSUE TITLE
No package 'sndfile' found

### ISSUE THREAD

**Issue by xerhard** [ayyi/samplecat#58]
Installing on Ubuntu 20.04

output of ./configure

```
checking for sndfile... no
configure: error: Package requirements (sndfile) were not met:

No package 'sndfile' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SNDFILE_CFLAGS
and SNDFILE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by ayyi** [comment]
Hi

I guess you are seeing this because you do not have libsndfile installed.

However this does raise the point that it should be possible to make libsndfile optional now. Audio files can either be handled by libsndfile, or ffmpeg. It is recommended to use libsndfile if you are using WAV files because it is more accurate.

I will look into making libsndfile an optional dependency...

Thanks

**Comment by xerhard** [comment]
Solved it with:
`sudo apt-get install libsndfile1-dev`

during some itterations I also needed to install: libxml2, libxml2-dev, gtk2.0, libgraphene-1.0-dev 

No it build succesfully
